### ISSUE TITLE
Research Server Option: Lightsail

### ISSUE THREAD

**Issue by coultergeist** [ActoKids/AD440_W19_CloudPracticum#10]
Phu: Research feasibility of AWS server option LightSail.

Estimated Time:
Actual Time:

**Comment by zphupro** [comment]
I am doing Research on Amazon Lightsail what good about light sail and what option and I read docs on lightsail 's website. I also read the review from Users who already used light sail and what they thought about that. I watch video on Youtube  it shows you from setup to config on lightsail it's very useful 
Estimated Time: 7 hours

**Comment by toddysm** [comment]
At the end of the sprint can we get the following:

- Lightsail instance
- Running web server (NGINX or Apache)
- Can load the home page for the web server?

As part of the documentation, we have links to how do you set up and the link to the web server to load the page.

**Comment by zphupro** [comment]
Estimated Time: 7
Actual Time: 6 
amazon Lightsail is a cloud platform that's cost-effective, fast, & reliable with an easy-to-use interface. It’s ideal for simpler workloads, quick deployments, and getting started on AWS.
http://35.165.28.237/
The difficult I facing ii try to config the Apache config file to my folder but it still doesn't work.

**Comment by zphupro** [comment]
my documentation  : https://github.com/ActoKids/web-ui/wiki/Research-Server-Option:-Lightsail
