### ISSUE TITLE
UI Team connection to DynamoDB

### ISSUE THREAD

**Issue by hkhual** [ActoKids/AD440_W19_CloudPracticum#104]
Need to connect to dynomodb to confirm user login, issue #93 .

Intentional note: This impacts the final demo issue #91

**Comment by ZakBrinlee** [comment]
UI Team - Please provide more information and follow the BUG template provided by Toddy in class. 

There is no way to connect to DynamoDB from the UI. Also, there is no user information in the database.

Regarding issue #93, the logic for fixing the UI components will be entirely in React. You will need to set logic in your Nav component on what to show depending on if the user has been authenticated. 

**Please confirm if this BUG needs to remain open and further help from API Team.**

**Comment by hkhual** [comment]
As Zak mentioned here, UI cannot connect directly to DynomoDB but through API endpoint.
