### ISSUE TITLE
BUG: GET endpoint for all events malfunctioning

### ISSUE THREAD

**Issue by erikNeville** [ActoKids/AD440_W19_CloudPracticum#106]
This bug also addresses the issue presented in bug: https://github.com/ActoKids/AD440_W19_CloudPracticum/issues/104

Environment: API GET event method
Current Behavior: API call is returning invalid JSON data
Expected Behavior: API GET call to return valid JSON data

There was a miscommunication about the UI retrieving data from DynamoDB and how it was all meant to be from a call to the API GET method. @hkhual Opened the bug mentioned above and it is since now resolved.

The API endpoint https://api.2edusite.com/v1/events was providing the UI team with data that was formatted with invalid JSON data that could not be parsed:
![image](https://user-images.githubusercontent.com/27576296/54162337-679db680-4412-11e9-9f2f-c932a00facea.png)

The `\`'s before each key prevented us from calling GET to the API.

@ZakBrinlee Worked on his end to eliminate the superfluous `\`'s at that endpoint:
 
![image](https://user-images.githubusercontent.com/27576296/54162418-a16ebd00-4412-11e9-8623-027ab9f441e6.png)

Currently the data at that endpoint looks like this:
![valid-json](https://user-images.githubusercontent.com/27576296/54162473-d24ef200-4412-11e9-8b19-9a010f5af142.PNG)

**Comment by ZakBrinlee** [comment]
**Issue:** 
- Line 45 : 'responseBody = JSON.stringify(data)'; 
   - Prior to UI team bringing up the bug to myself, the 'data' coming from DynamoDB was being wrapped with JSON.stringify() method. 
   - This was on purpose for the visual demonstration for prior Sprints as it puts the JSON data into a more readable String format. 

**Solution:**
- Removed the JSON.stringify() from the JSON data coming from DynamoDB. 
- 'responseBody = data;' 

![LambdaBUGFix](https://user-images.githubusercontent.com/22527777/54166275-c0c11680-4421-11e9-8e61-ffb49b298ec8.PNG)

Closing this issue as Erik has indicated it has been resolved to the satisfaction of UI Team.
