### ISSUE TITLE
BUG: No 'Access-Controll-Allow-Origin'...

### ISSUE THREAD

**Issue by erikNeville** [ActoKids/AD440_W19_CloudPracticum#107]
Issue with access control due to the header being present on the requested resource.

I am trying to use the event_id, which is generated through AWS, as a way to pass props to another react Component, and I am receiving this error: `No 'Access-Control-Allow-Origin' header is present on the requested resource`

Here is a shot of there being no issues with CORS headers on our dashboard:
![working-api-dashboard](https://user-images.githubusercontent.com/27576296/54175874-bfa3df80-4449-11e9-98f9-7a9e9bd76bb3.PNG)

And a shot of the error I get when I try to use the ID in a header:
![network-error](https://user-images.githubusercontent.com/27576296/54175901-d0545580-4449-11e9-90de-3d85fe35ea9e.PNG)

A link I've been reading through to understand this issue: https://serverless-stack.com/chapters/handle-api-gateway-cors-errors.html

**Comment by erikNeville** [comment]
For further understanding of what I'm trying to do, here is my commit for the code I have so far:
https://github.com/ActoKids/web-ui/pull/34/commits/f6f3911b14cbc165b7f457f4bd27c33ccd3497a7

**Comment by Enshaedn** [comment]
I think the error is in your URL / endpoint call. I've marked the line in your code with a comment, but essentially it looks like you're trying to call /v1/event/{event_id}, but that is not a valid endpoint. The endpoint is /v1/event**s**/{event_id}.

Presuming you're just trying to GET by id:
![image](https://user-images.githubusercontent.com/23545971/54177598-01378900-4450-11e9-8a29-19bf12d857b2.png)

That is the same event_id and it works as a GET.
