### ISSUE TITLE
BUG: Error in Google Crawler logs

### ISSUE THREAD

**Issue by daonguyen81** [ActoKids/AD440_W19_CloudPracticum#108]
The Google Calendar passed the test multiple times, however there is error and warning found in the logs.
ModuleNotFoundError: No module named 'google.appengine'

,,,
START RequestId: 07933b17-53ca-4925-900f-0b3e0712292f Version: $LATEST
[WARNING]	2019-03-12T18:36:24.570Z	07933b17-53ca-4925-900f-0b3e0712292f	file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
Traceback (most recent call last):
  File "/var/task/googleapiclient/discovery_cache/__init__.py", line 36, in autodetect
    from google.appengine.api import memcache
ModuleNotFoundError: No module named 'google.appengine'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/googleapiclient/discovery_cache/file_cache.py", line 33, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client.contrib.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/googleapiclient/discovery_cache/file_cache.py", line 37, in <module>
    from oauth2client.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/var/task/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-authStarting GoogleCalendar crawler;  2019-03-12 18:36:25.324551
Opening calendars: Success
Closing GoogleCalendar crawler;  2019-03-12 18:36:30.559977
END RequestId: 07933b17-53ca-4925-900f-0b3e0712292f
REPORT RequestId: 07933b17-53ca-4925-900f-0b3e0712292f	Duration: 6302.86 ms	Billed Duration: 6400 ms 	Memory Size: 128 MB	Max Memory Used: 94 MB
,,,

**Comment by MikeJLeon** [comment]
This bug was not fixed. I will now close this issue as we are doing with this project.
