### ISSUE TITLE
Research server option: Fargate

### ISSUE THREAD

**Issue by coultergeist** [ActoKids/AD440_W19_CloudPracticum#11]
Research feasibility of the AWS server option Fargate

Estimated Time:
Actual Time:

**Comment by hkhual** [comment]
I am going to give this task about 5 hours. Because going to watch tutorial videos to familiar myself on AWS Fargate service.

**Comment by toddysm** [comment]
The final deliverable for this is:

- Fargate instance
- Web server running on the Fargate instance (NGINX or Apache)
- Can load the home page of the web server?

**Comment by hkhual** [comment]
Estimated time: 5 hours
Actual time: 6 hours 
Did some reading on docs. 
1. Reading AWS Elastic Container Service (ECS) doc. https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ECS_GetStarted_EC2.html
2. Read AWS Fargate on ECS document https://docs.aws.amazon.com/AmazonECS/latest/developerguide/AWS_Fargate.html 
3. watched AWS Fargate tutorial video https://www.youtube.com/watch?v=IEvLkwdFgnU  

Fargate is a compute engine for Amazon Elastic Container Service (ECS). It is a highly scalable, high performance container orchestration service. It is basically an engine for ECS to manage the container's underlining services.  
I do think AWS Fargate is a great service for running containers  and no clusters to manage but you have less control of your server clusters.

**Comment by hkhual** [comment]
![fargate actokids 4](https://user-images.githubusercontent.com/24612635/51596004-d9df2980-1eac-11e9-9e98-3c6044a6348e.JPG)

Created Fargate cluster

**Comment by hkhual** [comment]
![fargate actokids 2](https://user-images.githubusercontent.com/24612635/51596364-a81a9280-1ead-11e9-8a38-13a4c668b928.JPG)
Created Fargate instance running nginx web server.

**Comment by hkhual** [comment]
Here is the [Homepage for web server](http://3.86.31.50/). This is testing to make sure it can load the homepage for the web server.

**Comment by hkhual** [comment]
Here is the wiki page: https://github.com/ActoKids/web-ui/wiki/Research-Server-Option:-Fargate
