### ISSUE TITLE
Bug: UI elements which call API aren't set up for a new API format

### ISSUE THREAD

**Issue by erikNeville** [ActoKids/AD440_W19_CloudPracticum#112]
The standard format that was agreed on weeks ago seems to be changing. So the UI no longer accepts this new format that seems to be implemented now. This involves a large overhaul of UI elements and formatting. 

Here's now the API looks as of right now:
![api-format-3 13 2200](https://user-images.githubusercontent.com/27576296/54332630-44266780-45dc-11e9-8a9a-890372ae6599.PNG)

Here's a code example of how we were using the OLD API structure:
![how-code-comes-from-API-3 13 2200](https://user-images.githubusercontent.com/27576296/54332647-57393780-45dc-11e9-9a51-f4d693400166.PNG)

Here's how that looks on the front end now:
![dashboard-pulling-from-API-3 13 2200](https://user-images.githubusercontent.com/27576296/54332654-6324f980-45dc-11e9-9f88-20136dd491e4.PNG)

Notice how the UI relies on objects called location_name, location_address, contact_name, contact_phone, and many which have either changed or do not exist any longer.

**Comment by MikeJLeon** [comment]
We simply just didn't have those fields. If you need us to generate a default value just for it to have something to display, let me know. This is a 5 minute fix if we go with the default value route.

**Comment by MikeJLeon** [comment]
In addition I have fixed the start time not appearing for events that did have it.
Please observe the following link : https://localendar.com/event?DAM=PublishedEvent&m=333899&event_id=1442&calendar_id=333899&more_info=N&export_date=Mar%2016,%202019&category=8

This is the example you used in your screenshot. This event only gave us the name, other times we get a full address. This cannot be addressed.

There will be a few dud's like this.

**Comment by erikNeville** [comment]
To further understand how the UI team has been implementing GET through the API see this link: https://github.com/ActoKids/api/wiki/GET-Request-for-Events

and: https://8cex032b53.execute-api.us-west-2.amazonaws.com/sprint2_test/v1/events

Although the endpoint has changed, that is the JSON structure that the UI relies on.

This bug also pertains to the bug linked to here: https://github.com/ActoKids/web-crawler/issues/20

**Comment by erikNeville** [comment]
@MikeJLeon  and I came up with an agreed upon default value for each database key. @rberry206 and @MikeJLeon helped implement those, and the UI team now knows which calls to make. This issue is closed.
