### ISSUE TITLE
Bug: Automated Deployment of Build to S3

### ISSUE THREAD

**Issue by erikNeville** [ActoKids/AD440_W19_CloudPracticum#113]
Two web-ui dev mergers have taken place and there doesn't seem to be any deployment to prod/dev endpoints. Visit [2edusite.com](url) or [www.2edusite.com](url) 

What is displayed at those endpoints does not match the working build of the current UI merge.

Here are links to the PRs which were merged:
https://github.com/ActoKids/web-ui/pull/36

https://github.com/ActoKids/web-ui/pull/34

**Comment by dashinay** [comment]
Anything that gets merged into the dev branch will trigger the Travis Ci to deploy it into the dev environment which is the endpoint www-dev.2edusite.com. For Travis Ci to start doing any deployment into prod endpoint a code should be merged into prod branch (which in our case pull requesting the dev branch code into the prod branch.) 
So overall: 
pull requests into dev branch is reflected in www-dev.2edusite.com endpoint
pull request into prod branch is reflected in www.2edusite.com and 2edusite.com endpoints

Could you check the www-dev.2edusite.com to see the changes you have made?

**Comment by erikNeville** [comment]
Looks good thanks @dashinay , We will make sure the prod branch automation works soon. For now www-dev.2edusite.com is up and running.
