### ISSUE TITLE
Bug: Formatting Date/Time Using React

### ISSUE THREAD

**Issue by erikNeville** [ActoKids/AD440_W19_CloudPracticum#114]
The format that our "start_date_time" and "end_date_time" fields appear is YYYY-MM-ddThh:mm:ss.000Z. I have been trying to reformat that style, but without much experience with react I am having trouble with displaying that in a proper way. 

![datetime](https://user-images.githubusercontent.com/27576296/54411284-08f36980-46ac-11e9-9130-86c9bb7d2b89.PNG)

That shows the way it looks: 2019-03-20T10:00:00.000Z.
I'm trying to format it as March 3, 2019 10:00. I know how to do this without using react, but I'm in need of help on how to do it with react.

**Comment by hkhual** [comment]
@erikNeville I think you can use pure javascript to convert those timestamp into the format you want. But I found an external library like moment.js, is the best way to convert those timestamps. 
I was able to format like March 3, 2019 10:00 by using Moment.js. If you want to test it. Here is the link https://momentjs.com/
![timestamp-d1](https://user-images.githubusercontent.com/24612635/54416826-b91d9e00-46bd-11e9-83ab-a9ae4816f350.png)

**Comment by erikNeville** [comment]
Thanks @hkhual , got it working using Momentjs
