### ISSUE TITLE
Bug: Recieving this error when trying to GET from API

### ISSUE THREAD

**Issue by erikNeville** [ActoKids/AD440_W19_CloudPracticum#119]
Here is the error: Access to XMLHttpRequest at 'https://api.2edusite.com/v1/events' from origin 'http://localhost:3000' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header contains the invalid value '2edusite.com'.

The UI team has not changed how we were accessing the API and using GET to fill all UI elements. We need guidance as to where this error is coming from.

**Comment by T-travis** [comment]
The Integrations Response in API Gateway was set wrong.  There were to many values not needed added.  All it needed was just this: 
![image](https://user-images.githubusercontent.com/25231407/54572294-02167080-49a4-11e9-9ac0-ef7ecbf0e906.png)
Problem solved
