### ISSUE TITLE
Calling API from browser

### ISSUE THREAD

**Issue by coultergeist** [ActoKids/AD440_W19_CloudPracticum#12]
Erik: Working with the API team, call API from the browser

Estimated Time: 
Actual Time: 1 hr

Wrote HTML with javascript which pulls from the Lambda function API.
[index.txt](https://github.com/ActoKids/AD440_W19_CloudPracticum/files/2766910/index.txt)

**Comment by erikNeville** [comment]
Wrote html file containing javascript which pulls from the API.
[index.txt](https://github.com/ActoKids/AD440_W19_CloudPracticum/files/2766907/index.txt)

**Comment by erikNeville** [comment]
https://github.com/ActoKids/web-ui/wiki/Calling-API-From-Browser

For Documentation
