### ISSUE TITLE
Bug: AWS Cognito not functioning 

### ISSUE THREAD

**Issue by coultergeist** [ActoKids/AD440_W19_CloudPracticum#120]
@hkhual, at the `if(!auth) return <Redirect to='/' />` (line 100 on Dashboard.js) the redirect should call the dashboard. Right now it goes back to signin page.

**Comment by hkhual** [comment]
@coultergeist Redirect call is functioning as expected what is not functioning is isAuthenticated Session. 
isAutenticated clear the session whenever the user refresh the page.

**Comment by hkhual** [comment]
I believe the problem might be cause by Auth.currentSession() method in aws simplify, AWS simplify can't authenticate user because there is problem connecting to AWS Cognito.

**Comment by hkhual** [comment]
**Here when tried to login it display saying user does not exit. This error has to do with AWS Cognito.** 
![user does not exit](https://user-images.githubusercontent.com/24612635/54715172-0790c980-4b10-11e9-96c4-f08578fc3b6d.JPG)
