### ISSUE TITLE
Bug: Environmental variable and timer required for OFAScraper_prod

### ISSUE THREAD

**Issue by mrvirus9898** [ActoKids/AD440_W19_CloudPracticum#122]
The OFAScraper_prod is almost ready for prime time, but it needs two things first:

![path requirements](https://user-images.githubusercontent.com/19317411/54660462-c9ee5b00-4a93-11e9-9072-68345676a16d.png)

A PATH Environmental Variable needs to be set, that targets /var/task/bin/. The picture above is an example of what this should look like. As a Non-dev ops member, I can not change this myself.

Second, the timer will need to be change to 10 mins. This is to give the lambda additional time to execute it's required tasks.

@Stakada @jams2018 @bmenaz assigned because they have worked on these in the past, feel free to reassign as appropriate. Thank you for all your work.

**Comment by jams2018** [comment]
working on it.

**Comment by jams2018** [comment]
![environment](https://user-images.githubusercontent.com/38123178/54661249-aa0c6680-4a96-11e9-9cde-c6e714b4d1f4.PNG)
![execution](https://user-images.githubusercontent.com/38123178/54661250-aa0c6680-4a96-11e9-9b40-e95ed4d2edf8.PNG)

**Comment by jams2018** [comment]
Both the requested changes have been made. Would you check them and close the ticket if they are fulfilled?

**Comment by mrvirus9898** [comment]
Confirmed! You are on it man!
