### ISSUE TITLE
Permission for Dynamo Production Table

### ISSUE THREAD

**Issue by MikeJLeon** [ActoKids/AD440_W19_CloudPracticum#123]
@Stakada Hey could you give me full permission to the dynamo production table ak-prod-events-dynamo @ActoKids/devops

**Comment by Stakada** [comment]
I created a new policy and attached to you.

**Comment by Stakada** [comment]
**New Policy** : https://console.aws.amazon.com/iam/home?region=us-west-2#/policies/arn:aws:iam::061431082068:policy/ad440-w19-dynamodb-crawler$jsonEditor

**Comment by MikeJLeon** [comment]
Thanks shota! I have full permission to what I need.
