### ISSUE TITLE
Research deploying to S3 in AWS. 

### ISSUE THREAD

**Issue by LyndonP** [ActoKids/AD440_W19_CloudPracticum#14]

**Comment by amy61789** [comment]
Resources Reviewed:
https://docs.aws.amazon.com/AmazonS3/latest/dev/Welcome.html
https://docs.aws.amazon.com/AmazonS3/latest/user-guide/create-configure-bucket.html
https://docs.aws.amazon.com/AmazonS3/latest/dev/Welcome.html
Need:
What are we deploying to the s3 buckets? static web page, images, etc
Estimated Time:
2 hours

**Comment by amy61789** [comment]
Deliverable for end of sprint: Create the pipeline for s3
Estimated time: 4-5 hours, I haven't done any continuous deployment or used Travis CI before.
Starting research of Travis CI to implement CD in an s3 bucket. Going to begin coding what I can until Yahya finishes creating a demo app to deploy via s3.

**Comment by amy61789** [comment]
Endpoint: https://s3.us-east-2.amazonaws.com/travis-demo-sprint1/index.html
Deployed Travis CI s3 on my personal Github & AWS account - needed too many permissions to use the teams AWS account. Travis CI documentation is lacking, most tutorials over 2+ years old.
Used this tutorial as a guide: https://medium.com/@michal.frystacky/static-site-github-to-s3-770953a90f67
Was able to deploy a static website on an s3 bucket.
Actual Time it Took: 6 hours - got snagged up on documentation and finally just blew away the initial attempt to start from scratch to go over details of implementation.
