### ISSUE TITLE
Fetch data from webpage

### ISSUE THREAD

**Issue by mrvirus9898** [ActoKids/AD440_W19_CloudPracticum#17]
Write a script to fetch data from a webpage. This script may fetch any data at this time, and is to be a reference for future code. @MikeJLeon has already posted such a script. Feel free to download your own copy and play with it. @MikeJLeon feel free to mark this issue as closed at will. 

Please indicate the time spent on this, any issues that you are having, any good references you found for this subject, and credit anyone helped you out.

**Comment by MikeJLeon** [comment]
As of the initial commit it took me roughly 5 hours to figure it out. I'm going to try to make it more complex and will leave this open for the time being.

**Comment by MikeJLeon** [comment]
I've spent about 20 hours tinkering and messing with my new code. I've also created a wiki page talking about my crawler under "WebCrawler". 

I just need a review of my code then we can push this to complete.

**Comment by MikeJLeon** [comment]
Code reviewed by two. Moved card to done

Actual Time  : 24 hours

**Comment by MikeJLeon** [comment]
added wiki - https://github.com/ActoKids/AD440_W19_CloudPracticum/wiki/WebCrawler
