### ISSUE TITLE
Fetch data from Google Calendar

### ISSUE THREAD

**Issue by mrvirus9898** [ActoKids/AD440_W19_CloudPracticum#18]
Some of our partner organizations use Google Calendars to schedule and keep track their events. As such we will need a way to fetch their data using Google's API. Previous code used Postman and Javascript, however our crawlers will need to use Python; thus Python code is required.

Please indicate the time spent on this, any issues that you are having, any good references you found for this subject, and credit anyone helped you out.

**Comment by rberry206** [comment]
I spent a whopping 10 minutes on the code with my own Google Play Dev key. Just copied the code from https://developers.google.com/calendar/quickstart/python, made my own events on the calendar to test. Works well in the console.

**Comment by rberry206** [comment]
![calendarcrawler](https://user-images.githubusercontent.com/34557901/51631985-09b91c00-1f03-11e9-8f8c-6d112512f741.gif)

**Comment by rberry206** [comment]
Steps:
1. Install python
2. Turn on the Google Calendar API, move the downloaded file to the directory and name is credentials.json
- I used my own Google Play Token and my own calendar for testing
3. Install the Google Client Library (seen in the GIF)
4. Setup the sample (copy the code from online), name the file whatever you'd like.
5. Run your sample with 'python' + space + file name

Next Steps:
- Convert output to JSON
- Increase output for more information
- Find what data can possibly be returned by Google Calendars

**Comment by rberry206** [comment]
Here's the Wiki for the updated version https://github.com/ActoKids/web-crawler/wiki/Google-Calendar
