### ISSUE TITLE
Data Model - Create JSON file

### ISSUE THREAD

**Issue by Enshaedn** [ActoKids/AD440_W19_CloudPracticum#2]
For Karen
@ActoKids/api

**Comment by toddysm** [comment]
Deliverable - JSON describing the event

**Comment by kdanepetersen** [comment]
based on admin functionality (create event)

**Comment by kdanepetersen** [comment]
Nick said he can easily update the names if I change them.

**Comment by kdanepetersen** [comment]
Estimated Time: 8 hours
Current Actual Time:  4 hours

1.  Obtained existing list or organizations and JSON from Zach and made a temporary JSON file using this information along with additional fields suggested by Cheryl Kerfeld during the first class.
2.  Viewed a youtube video on the Acto Kids mobile app and made a list of data from screens displayed on the video.
3.  Contacted UI team to get a contact for wireframes and requested a copy of wireframes to confirm what data is needed.
4.  Slacked Kyrrah to get a contact name for scraper team that will need the data model
5.  Researched software for data modeling (chose Visio)
6.  Researched naming conventions for database data modeling and started defining the naming conventions.
7.  Sent slack message to Lyndon to get my email added to github so I can create / update project tasks.

**Comment by kdanepetersen** [comment]
research information about json files
research information about data diagrams
review information about github
review mobile actokids application
obtain and review original json, original organization list to determine data needed.
create json file for events.
review with API, UI, and Crawler teams for feedback.
Push to github

Estimated hours:12
Actual Hours: 12

**Comment by kdanepetersen** [comment]
{
   event": {
             “id”: “this is the event id”,
             “user_name”: “this is the name of the user that is entering the event”,
             “name”: “this is the short-name for the event, e.g., Fun with Yoga, Soccer, Art Walk”,
             “activity_type”: “this is an activity type, event title, based on activity filter including Outdoors & Nature, Music, Art, Museum, Sports, Zoo, Camp, Other for this event”,		
             “description”: “This is a long description of the event being held”,
             “org_name”: “this is the organization name holding the event”,
             “location_name”: “this is the name of the location where the event is being held”,
             “location_address”: “this is the street address, city, state & zip for the event being held”,
             “contact_name”: “this is the contact name for the event”,
             “contact_phone”: “this is the event contact’s phone number”,
             “contact_email”: “this is the event contact’s email address”,
             “start_date_time”: “event date and start time”;
             “end_date_time”: “event to time in military time timestamp”,
             “frequency”: “one time, versus reoccurring (weekly, monthly)”,
             “cost”: “this is the cost of the event”,
             “picture_url_”: “this is the url for the image displayed with the event information”,
             “min_age”: “this is the minimum age of the event participant”,
             “max_age”: “this is the maximum age of the event participant”, 
             “disability_types”: “this is a list of the disability types based on the filters including Cognitive, Sensory, Vision, Mobility, Hearing, Wheelchair bathrooms, adaptive equipment, targeted-available for this event”,
           }
}

**Comment by kdanepetersen** [comment]
file is called event.json

**Comment by kdanepetersen** [comment]
**Final Comment Required Information**

**Status**: in Progress - waiting on final Wireframes, UI and Web Crawler team approvals

**Estimated Time         Time Spent**


**Link to your pull request**
(link to code)

**Link to your Wiki Page**
(Describe how feature was implemented, automation script inputs, link to swagger, link to inputs and outputs)
Wiki Page:  https://github.com/ActoKids/AD440_W19_CloudPracticum/wiki/ActoKids-JSON-Example/


**API – link to deployed code** 
(http:// end point, using curl or postman to test that can be clicked on to see work)
