### ISSUE TITLE
Crawler Flowchart

### ISSUE THREAD

**Issue by mrvirus9898** [ActoKids/AD440_W19_CloudPracticum#26]
Please create a flowchart describing the work flow and logic of the crawlers. Start with the trigger, and end with sending the JSON to the designated API. Dont be afraid to break a crawler up into several functions/Lambdas for ease of development.

Extension of #21 

Please indicate the time spent on this, any issues that you are having, any good references you found for this subject, and credit anyone helped you out.

**Comment by kyrrahnork** [comment]
Estimated time to complete: 2 hours
Actual time to complete: 2.5 hours

**Comment by mrvirus9898** [comment]
https://drive.google.com/file/d/1cMdFaKzJlw2Y4q16XX6cHwxwHdjn42Ls/view?usp=drivesdk
