### ISSUE TITLE
Create POST request for events

### ISSUE THREAD

**Issue by ZakBrinlee** [ActoKids/AD440_W19_CloudPracticum#32]
Create POST request for events showing on Dashboard

Estimated time: 7 hours

Actual time:

**Comment by Enshaedn** [comment]
Currently working on it. Haven't made an actual API previously or used Node. Lots of research going on. 

~2 hours spent so far. Built an HTML form for testing purposes at [enshaedn.com](http://enshaedn.com)

**Comment by Enshaedn** [comment]
Scrapped HTML form per instructions. Currently have API Gateway connected to Lambda and through to DynamoDB. 

Getting the set up was rather tricky, but I've been keeping notes in OneNote and will create a wiki before the end of the sprint. 

Currently an additional 8 hours spent. GET https://api.enshaedn.com/v1/events currently works for demo purposes - next step is to finish the POST operation.

**Comment by Enshaedn** [comment]
Estimated Time: 7 hours
Actual Time: 15 hours

[Pull Request](https://github.com/ActoKids/api/pull/9)
[Wiki](https://github.com/ActoKids/api/wiki/POST-Request-For-Events) - Demo included in Wiki
No deployed code yet - No access to class AWS. 

Pull Request reviewed by Zak and Travis.
As for testing, I did some, but it was mostly trial and error of POST requests. Seeing what was accepted/rejected, and the http codes returned.

I reviewed Zak's [(PR 14)](https://github.com/ActoKids/api/pull/14), Travis' [(PR 27)](https://github.com/ActoKids/api/pull/27) & [(PR 13)](https://github.com/ActoKids/api/pull/13), and Jon's [(PR 23)](https://github.com/ActoKids/api/pull/23) pull requests.
