### ISSUE TITLE
Create PUT request for events

### ISSUE THREAD

**Issue by ZakBrinlee** [ActoKids/AD440_W19_CloudPracticum#34]
Create PUT request for editing events showing on Dashboard
Estimated time:
Actual time:

**I am closing this task and re-creating it in the API repo.**

**Karen has requested to be removed from this task. It will be re-assigned to a different member of the API Team**

**New Issue: [Create PUT request for Events with logging](https://github.com/ActoKids/api/issues/52)**

**Comment by kdanepetersen** [comment]
Estimated Time      Actual Time     Task Description
------------------------------------------------------------------------------------------------------------------
4 hours                   3 hours            API Training
4 hours                   0 hours            node.js training
4 hours                   0 hours            javascript refresher 
4 hours                   2 hours            HTML/CSS refersher
4 hours                   0 hours            Lambda training
2 hours                   0 hours            Set up software for local development (mongo DB, AWS services etc)
8 hours                   1 hours            code software for put request in nodejs, javascript
8 hours                   0 hours            test put request
4 hours                   0 hours            push put request to github

**Comment by toddysm** [comment]
Need the following:
- Link to Pull Request
- Link to Wiki page
- Who tested this and feedback?
- What did you test and your feedback?

**Comment by kdanepetersen** [comment]
Additional training hours:  12

**Comment by ZakBrinlee** [comment]
I am closing this task and re-creating it in the API repo. 

Karen has requested to be removed from this task. It will be re-assigned to a different member of the API Team

New Issue: [Create PUT request for Events with logging](https://github.com/ActoKids/api/issues/52)
