### ISSUE TITLE
Create Org/Super Admin Dashboard

### ISSUE THREAD

**Issue by erikNeville** [ActoKids/AD440_W19_CloudPracticum#35]
Create the dashboard for the two types of users, organization admin and super admin. The two dashboards will be identical; the information presented on either dashboard will be determined post authentication at login.

Expected time: 5 hours
Actual Time:

**Comment by erikNeville** [comment]
Created a react web application locally with scrolling event list. My challenge so far has been teaching myself to create react apps for browser instead of react-native for mobile. So far 4 hours logged on this task.

**Comment by erikNeville** [comment]
I have a list of event information with dummy data for events. I do not know how to call from the API to load event info yet. At this stage I'm focusing on making the list view look better for a better user experience. I need to add the formatting to make it resemble the wireframe that Danielle has created.
So far I am 8 hours invested in the Dashboard screen.

**Comment by erikNeville** [comment]
This is the progress I have made so far:

http://actokidsdashboard.s3-website.us-east-2.amazonaws.com

I still need to style to match the wireframe. The next step would be connecting the relevant table portions with calls to the API, and adding buttons that will allow a user to create, update, or delete an event.

I still need to link this Dashboard to the login page. The dashboard displayed will be determined by the auth credentials of the user logging in.

A link to the wiki page is here:
https://github.com/ActoKids/web-ui/wiki/Dashboard

Total time spend so far: 12 hours.

**Comment by toddysm** [comment]
Few questions:
- How do I submit the changes to the backend? For example, when I want to approve or deny events, what triggers the call to the backend?
- On the wiki page, can you explain how this works internally in React?
- Is there a code commit for this task? I don't see anything linked to the issue in Github.
- Who tested this and did they find any issues?

**Comment by erikNeville** [comment]
Our GitHub file and folder structure is in the process of being revamped now that each page is completed. The changes to that will be available on Sunday. Once the update is made each team member will be able to successfully merge their changes to their assigned pages. Right now changes submitted to the backend are through firebase. This is for testing purposes until the API team has a GET method created. As of right now there are no requests for approving or denying an event because we don't have a full API to make calls to.

**Comment by erikNeville** [comment]
Final comment:

Estimated time: 5 hours
Total time: 10 hours

As of now there are no triggers pertaining to approving or denying an event. I assume that will have something to do with an API call, but I have research to do on that matter. 

Here is a link to my pull request: https://github.com/ActoKids/web-ui/pull/17

wiki link: https://github.com/ActoKids/web-ui/wiki/Dashboard
