### ISSUE TITLE
Create Login Page

### ISSUE THREAD

**Issue by erikNeville** [ActoKids/AD440_W19_CloudPracticum#36]

**Comment by hkhual** [comment]
Create a login page to allows organization admin and super admin to login. I will research on creating login page using React library.  After login page has been created, I’ll need to test the login page with fake API to if it can login. 
**Estimated time**: 7 hours
**Actual time:** TBD

**Comment by coultergeist** [comment]
![2-login](https://user-images.githubusercontent.com/16545169/52024732-b4f34380-24b6-11e9-8f6e-c1f66775f40e.jpg)

**Comment by hkhual** [comment]
Estimated time: 5 hours
Actual Time: 7 hours 
Being new to Reactjs myself, I found myself struggling to create login page using Reacjs framework. I watch tutorial videos to familiar myself with Reactjs framework. I did many researches and found some reactjs login page someone already created. I modified the reactjs login page and build on top of the login page. I did run into some issues trying to run the reactjs login page mainly due deprecated library.

**Comment by hkhual** [comment]
![sprint 2 register page](https://user-images.githubusercontent.com/24612635/52385464-8a653580-2a36-11e9-914e-b827efe35cd0.JPG)

**Comment by hkhual** [comment]
Here is the login page I uploaded to AWS S3 bucket: 
http://actokids.s3-website-us-east-1.amazonaws.com/

**Comment by toddysm** [comment]
Need the following things:
- Pull request link
- Link to Wiki page
- Who tested this and any feedback?
- What did you test and any feedback?

**Comment by hkhual** [comment]
Here is the pull request link. [Login page](https://github.com/ActoKids/web-ui/pull/9)
Link to [Wiki page](https://github.com/ActoKids/web-ui/wiki/LoginPage)
. Two of my team members (Zphu and Erik ) tested and gave feedback. You could check their feedback in the pull request.
. Tested hard-coded username and password into login page and can successfully login. 
Here is the link to login page hosted on AWS S3 [Login page](http://actokids.s3-website-us-east-1.amazonaws.com/)

**Comment by hkhual** [comment]
For testing. I test whether admin/super admin can login to dashboard using fake backend.
