### ISSUE TITLE
Create 'Add Event' Page

### ISSUE THREAD

**Issue by erikNeville** [ActoKids/AD440_W19_CloudPracticum#37]

**Comment by bradleyshao** [comment]
Estimate time: 10 hrs
https://reactjs.org/
I did some research about React and i will work with Phu together, because our task is similiar. We will do some research about to generate a JSON from our test page.

**Comment by bradleyshao** [comment]
Estimate time: 10 hrs
Actual time: 12 hrs
I don't have experience about React, so I spent lots of time for researching React.
https://reactjs.org/docs/getting-started.html
I decided to use material-ui instead of bootstrap.
https://material-ui.com/

**Comment by bradleyshao** [comment]
<img width="1280" alt="2019-02-05 18 26 47" src="https://user-images.githubusercontent.com/34496812/52317921-0304bd00-2977-11e9-9e82-d120068a572b.png">

**Comment by bradleyshao** [comment]
<img width="1280" alt="2019-02-05 18 27 25" src="https://user-images.githubusercontent.com/34496812/52317932-1152d900-2977-11e9-8ce1-06af00c6a974.png">

**Comment by bradleyshao** [comment]
<img width="1269" alt="2019-02-05 18 27 04" src="https://user-images.githubusercontent.com/34496812/52317946-19ab1400-2977-11e9-8e31-d337c9aacdb2.png">

**Comment by bradleyshao** [comment]
<img width="1267" alt="2019-02-05 18 27 18" src="https://user-images.githubusercontent.com/34496812/52317950-1e6fc800-2977-11e9-9cf6-db3911345f7f.png">

**Comment by bradleyshao** [comment]
<img width="1280" alt="2019-02-05 18 27 25" src="https://user-images.githubusercontent.com/34496812/52317956-229be580-2977-11e9-9e0b-095495e87fb8.png">

**Comment by bradleyshao** [comment]
https://github.com/ActoKids/web-ui/tree/yitong_addEvent

**Comment by bradleyshao** [comment]
http://addevent.s3-website-us-west-2.amazonaws.com

**Comment by toddysm** [comment]
We need a Wiki page describing how the implementation is done and describing the components in React.

Has somebody tested this and provided feedback?

**Comment by toddysm** [comment]
Also, you need to have Pull Request to the Dev branch.

**Comment by bradleyshao** [comment]
Wiki page --https://github.com/ActoKids/web-ui/wiki/Add-Event-Page

**Comment by bradleyshao** [comment]
https://github.com/ActoKids/web-ui/pull/12

**Comment by bradleyshao** [comment]
https://github.com/ActoKids/web-ui/pull/14

**Comment by bradleyshao** [comment]
<img width="1268" alt="2019-02-23 20 26 49" src="https://user-images.githubusercontent.com/34496812/53295135-6ed58b00-37a9-11e9-89d6-de450042c888.png">

**Comment by bradleyshao** [comment]
<img width="1266" alt="2019-02-23 20 27 00" src="https://user-images.githubusercontent.com/34496812/53295138-75fc9900-37a9-11e9-89cc-b23cd18961bd.png">

**Comment by bradleyshao** [comment]
This is the new version of the Create Event page. Use the materialize instead of the material-ui from old version, because Erik's dashboard use the materialize, and the material-ui can't be used together with materialize.

**Comment by bradleyshao** [comment]
Pull request----https://github.com/ActoKids/web-ui/pull/19
The pull request has been reviewed and does not have conflicts with dev branch. Merged.

**Comment by bradleyshao** [comment]
https://github.com/ActoKids/web-ui/wiki/Create-Event-(new-version)
