### ISSUE TITLE
Test - Save data in MongoDB (On AWS/Elsewhere)

### ISSUE THREAD

**Issue by Enshaedn** [ActoKids/AD440_W19_CloudPracticum#4]
@ActoKids/api

**Comment by T-travis** [comment]
I am looking into saving data on AWS and through other hosts using MongoDB.  I will be looking into MongoDB Atlas, mLab, and using an EC2 with MongoDB manually set up.  I will also be developing a demo of the EC2 instance with a test document being stored.  I estimate altogether this will take around 4 to 7 hours.

**Comment by T-travis** [comment]
Spent about 6 hours to finish research and ec2 demo

**Comment by T-travis** [comment]
See this [wiki](https://github.com/ActoKids/api/wiki/AWS-Database-Options) for details on the Database Options Research

**Comment by T-travis** [comment]
Complete this with DocumentDB: take Jon's code, write some code in node.js to call Jon's api and save data to DocumentDB (you can save a timestamp of when the api was called or whatever), have a way to show code to Toddy (add documentation in wiki or other and add comments to code) and have code working in a demo to test for him.  Talk with Zak, he is doing the same thing with DynamoDB.

**Comment by T-travis** [comment]
I'm gonna estimate at least 5 to 8 hours for this.

**Comment by T-travis** [comment]
Cost more than 60$ for one day of testing.  See this repo for code and notes in the README.md
https://github.com/T-travis/DocumentDB-Demo

**Comment by T-travis** [comment]
Completing this took about 8 hours.  Please see the [wiki](https://github.com/ActoKids/api/wiki/AWS-Database-Options) for details
