### ISSUE TITLE
Crawler Configuration

### ISSUE THREAD

**Issue by mrvirus9898** [ActoKids/AD440_W19_CloudPracticum#43]
It would be a poor engineering practice to have the entire crawler deployed as one linear Python file. Thus classes and modules should be explored and written to help break up our python code. Ideally, the crawler will select on the configuration and components it needs for a given website, so as to minimize it's execution time. This one is going to be a bit tricky so don't be afraid to reach out for help.

Please indicate the time spent on this, any issues that you are having, any good references you found for this subject, and credit anyone helped you out.

**Comment by daonguyen81** [comment]
Right now all our crawlers are in separate folder and file.
We have one main to call for each crawler separately.
We can add a menu to call each crawler based on the user input.

**Comment by daonguyen81** [comment]
Estimate time: 3 hrs.
Time spent: 2 hrs.
**Secret Manager with AWS.**
[Wiki](https://github.com/ActoKids/web-crawler/wiki/Secret-Manager)

**Comment by toddysm** [comment]
Is there any code for this? Wiki? Who tested this?

**Comment by daonguyen81** [comment]
@dashinay @LyndonP @amy61789 @Stakada @jams2018 
Can any of you from the DevOps team to review this idea for Secret Manager creating?

**Comment by daonguyen81** [comment]
[Wiki](https://github.com/ActoKids/web-crawler/wiki/Secret-Manager)
