### ISSUE TITLE
Logging from python code to AWS service (which one)

### ISSUE THREAD

**Issue by mrvirus9898** [ActoKids/AD440_W19_CloudPracticum#45]
The crawler will need to log code during it's normal and intended operation. Explore and write code that can log this data to a server. Touch base with the API team, and the Dev Ops team to see if they have a specific service for you to log to.

Please indicate the time spent on this, any issues that you are having, any good references you found for this subject, and credit anyone helped you out.

**Comment by kyrrahnork** [comment]
I estimated that this would take 4 hours.
It took 3.5 hours to complete.
Here is a link to the wiki page that documents what was done:
https://github.com/ActoKids/web-crawler/wiki/Lambda-that-logs-to-CloudWatch

**Comment by toddysm** [comment]
Few things:
- Accessing the URL throws Internal Server error
- Who tested this and what is her/his feedback?
- What did you test and what is your feedback?
