### ISSUE TITLE
UI Forms: Create>POST/events

### ISSUE THREAD

**Issue by coultergeist** [ActoKids/AD440_W19_CloudPracticum#49]
Connect forms to corresponding API endpoints: Create>POST/events

Once assigned, annotate your estimated time. Then, keep regular updates on your issue. Comment your approach, tutorials, articles, updates, links, photos, etc. Comment often. When closing your issue include the following in your final comment.

Time estimated:
Time spent:
Pull Request link:
Wiki link:
Deployed Code link:

**Comment by bradleyshao** [comment]
Estimate:10hrs
Currently, I reformatted the layout, trying to match the wireframe as much as possible, but the  'Slider' for cost and age range is still not working.  Will do more research on that.

**Comment by coultergeist** [comment]
Yitong, remember that you can abandon that age slider. It was just an idea for how to execute that but if it's hindering the task then feel free to choose an alternative method that enables the function.

**Comment by bradleyshao** [comment]
@coultergeist Great! Material Ui do have the 'Slider', but it's still in the 'Lab' category, I think that's why it's not work as i expected.

**Comment by bradleyshao** [comment]
Estimate :10 hrs
Actual : 14 hrs
Did lots of research about how to generate data to JSON format. Helpful Link : https://alligator.io/js/json-parse-stringify/
Also did lots of research about how to POST JSON data to the server. Helpful Link: https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch
https://www.robinwieruch.de/react-fetching-data/
And for the test purpose, I did lots of research about how to test POST on localhost. Helpful Link:https://scotch.io/tutorials/json-server-as-a-fake-rest-api-in-frontend-development

**Comment by bradleyshao** [comment]
<img width="1280" alt="2019-02-19 21 18 35" src="https://user-images.githubusercontent.com/34496812/53069674-a97db180-3491-11e9-970c-34879c63001b.png">
After install the json server, run the server on localhost:3000, the default json file have the empty values

**Comment by bradleyshao** [comment]
<img width="1269" alt="2019-02-19 21 20 47" src="https://user-images.githubusercontent.com/34496812/53069776-ff525980-3491-11e9-85b2-a5f5e735ba64.png">
Then run the add event project on localhost:3001. And enter the event information in the text area

**Comment by bradleyshao** [comment]
<img width="1265" alt="2019-02-19 21 20 29" src="https://user-images.githubusercontent.com/34496812/53069827-2e68cb00-3492-11e9-84d4-ee3879d265dc.png">

**Comment by bradleyshao** [comment]
<img width="1272" alt="2019-02-19 21 20 38" src="https://user-images.githubusercontent.com/34496812/53069848-36c10600-3492-11e9-8cb4-0fee5dfbd9b2.png">
Click continue button and jump to the review page, review all the information

**Comment by bradleyshao** [comment]
<img width="1280" alt="2019-02-19 21 21 27" src="https://user-images.githubusercontent.com/34496812/53069906-62dc8700-3492-11e9-906b-ba97a309d146.png">
Click the "Confirm & Continue" button after review, jump to the success page. The information data will be generated to JSON format.

**Comment by bradleyshao** [comment]
<img width="1280" alt="2019-02-19 21 21 39" src="https://user-images.githubusercontent.com/34496812/53069998-a33c0500-3492-11e9-85f7-ee514ff6998d.png">
Then back to the localhost:3000 (json server). All the information data has been updated to the server.

**Comment by bradleyshao** [comment]
https://github.com/ActoKids/AD440_W19_CloudPracticum/wiki/Post-Event

**Comment by Enshaedn** [comment]
The API endpoint for the POST method is: https://api.2edusite.com/v1/events

Please see the [data model wiki](https://github.com/ActoKids/api/wiki/Data-Model) and/or the [model event code](https://github.com/ActoKids/api/blob/dev/swagger/event_model.json) itself, and let us know if you have any questions.

**Comment by bradleyshao** [comment]
Actual: 14 hrs
Pull Request-----https://github.com/ActoKids/web-ui/pull/20
No conflicts with dev branch, merged

**Comment by bradleyshao** [comment]
<img width="649" alt="2019-02-25 12 29 32" src="https://user-images.githubusercontent.com/34496812/53368721-59be4080-38fe-11e9-8825-6b9ee52ebbc8.png">
<img width="761" alt="2019-02-25 12 31 52" src="https://user-images.githubusercontent.com/34496812/53368730-5d51c780-38fe-11e9-82bc-1f7b4f7f6cbc.png">
<img width="270" alt="2019-02-25 12 34 26" src="https://user-images.githubusercontent.com/34496812/53368742-62167b80-38fe-11e9-8d74-d526b2392ebe.png">
<img width="663" alt="2019-02-25 12 42 01" src="https://user-images.githubusercontent.com/34496812/53368754-69d62000-38fe-11e9-8088-844d8e4fefd6.png">
<img width="676" alt="2019-02-25 12 42 19" src="https://user-images.githubusercontent.com/34496812/53368758-6cd11080-38fe-11e9-8f6d-060cd6a73074.png">
<img width="371" alt="2019-02-25 12 42 32" src="https://user-images.githubusercontent.com/34496812/53368765-70649780-38fe-11e9-9904-4dc7515a12dd.png">
run ---  npm install -g json-server . --- to install the JSON server on local.
After that you can will find there is a folder called "json-server" has been created in the project folder.
Then create a json file called "event.json" , with default value.
After that call ---- ' json-server --watch event.json ' --- to run the server on localhost:3000
You can check the data at localhost:3000/values

**Comment by bradleyshao** [comment]
<img width="1280" alt="2019-02-25 13 02 19" src="https://user-images.githubusercontent.com/34496812/53369139-62fbdd00-38ff-11e9-8499-1f90f84c746a.png">
<img width="1270" alt="2019-02-25 13 05 24" src="https://user-images.githubusercontent.com/34496812/53369144-65f6cd80-38ff-11e9-87ac-715e637fbae3.png">
<img width="1273" alt="2019-02-25 13 05 44" src="https://user-images.githubusercontent.com/34496812/53369146-67c09100-38ff-11e9-9d3e-00946a2df086.png">
Then run the project on localhost:3001 , by running --- npm start
You will see the dashboard page once it runs.
Click create event button
Enter the information of event, click submit

**Comment by bradleyshao** [comment]
<img width="1269" alt="2019-02-23 21 16 56" src="https://user-images.githubusercontent.com/34496812/53296849-1dd58f00-37c9-11e9-9a50-b67bfab41021.png">

**Comment by bradleyshao** [comment]
<img width="1280" alt="2019-02-25 13 06 41" src="https://user-images.githubusercontent.com/34496812/53369327-cf76dc00-38ff-11e9-89b2-626944933207.png">
Then go back to the localhost:3000/values, refresh it, you will see the data has been updated

**Comment by bradleyshao** [comment]
<img width="1279" alt="2019-02-24 00 24 53" src="https://user-images.githubusercontent.com/34496812/53296950-a56fcd80-37ca-11e9-981f-87fea8902ab4.png">

**Comment by bradleyshao** [comment]
Estimate:10 hrs
Actual: 15 hrs
Pull Request-----[ActoKids/web-ui#20](https://github.com/ActoKids/web-ui/pull/20)
No conflicts with dev branch, merged
Teammate Phu and Hau reviewed and tested my pull request. You can check the feedback at the pull request link above. The main purpose of testing is make sure the fetch method can successfully upload user's input data to JSON server at local. The Wiki page below have the steps about how to setup and test at localhost. In sprint 4, I will connect my project with API team's endpoint instead of local json server, and reformat the data as well. 
Wiki-----https://github.com/ActoKids/web-ui/wiki/Post-Event
I have tested Phu's pull request and find out two bugs that need to be fixed.

**Comment by coultergeist** [comment]
Yitong, 
I tested this and it looks good! One thing, our fields need to match the API team's format of the JSON objects. I spoke with Alex and he said this is the latest version. We need to make sure our forms match this. Here's a link to the [most current JSON objects](https://github.com/ActoKids/api/wiki/Data-Model)

**Comment by bradleyshao** [comment]
@coultergeist
 Danielle,
 I know  we need to match with API team's JSON format, and I will do it in my sprint 4  task. But in my sprint 3 I just want to make sure that my fetch is working good. In sprint 4, I will connect my project with API team's endpoint instead of local json server, and reformat the data as well.  Thanks for remind me.
