### ISSUE TITLE
Cognito User Pool Login Page

### ISSUE THREAD

**Issue by zach-daniels** [ActoKids/AD440_W19_CloudPracticum#61]
We need a ui  User Pool login to get users into our Identity Pool. Once they're in the Identity Pool, we can use their identity id to get their temporary AWS credentials and test our AWS_IAM authorizer on our API Gateway.

**Comment by Enshaedn** [comment]
FYI - Had created this ticket for you in our repo. ;)

https://github.com/ActoKids/api/issues/19

**Comment by ZakBrinlee** [comment]
Closing this issue as it was resolved before. Zach and I created a UI login page to test this. 

Closing issue
