### ISSUE TITLE
Configure Dev endpoint

### ISSUE THREAD

**Issue by coultergeist** [ActoKids/AD440_W19_CloudPracticum#62]
Configure Dev endpoint. Work with Devops to test automation.

Once assigned, annotate your estimated time. Then, keep regular updates on your issue. Comment your approach, tutorials, articles, updates, links, photos, etc. Comment often. When closing your issue include the following in your final comment.

Time estimated: 
Time spent: 
Pull Request link: 
Wiki link: 
Deployed Code link: 
Testers:
What I tested:

**Comment by zphupro** [comment]
I will have working to map from the www-dev in a round 53  to www-dev s3 bucket to get endpoint link which will show The UI Website Team for testing.

Estimated time: 8 hrs

**Comment by zphupro** [comment]
This is my research website link that is help me setup this task 
https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/RoutingToS3Bucket.html
https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/getting-started.html#getting-started-create-s3-website-bucket

**Comment by dashinay** [comment]
I have tested the endpoint www-dev.2edusite.com and it fully function as it intented.

**Comment by bmenaz** [comment]
I have checked the route53 for the created record set and tested the endpoint that has been created.

**Comment by zphupro** [comment]
Time estimated: 8
Time spent: 8
Pull Request link: i don't have  pull request but I put all website to s3 bucket: https://s3.console.aws.amazon.com/s3/buckets/www-dev.2edusite.com/?region=us-east-1&tab=overview
Wiki link: https://github.com/ActoKids/web-ui/wiki/Configure-Dev-endpoint
Deployed Code link: http://www-dev.2edusite.com.s3-website.us-east-2.amazonaws.com/
Testers: 
 Dawit Ashinay: I have tested the endpoint www-dev.2edusite.com and it fully functions as it intended. he does automation 
bmenaz :I have checked the route53 for the created recordset and tested the endpoint that has been created.

What I tested:  
1# yitong create event ID 
https://github.com/ActoKids/web-ui/pull/29 
I tested on a local machine and it works perfectly when I click on create the event and fill out all information when I right click on inspect and go to console I saw I get event id from API. 
2# issue 
https://github.com/ActoKids/AD440_W19_CloudPracticum/issues/90
I found the issue that when going to the website and click on get data button and I got
404 Not Found
Code: NoSuchKey
Message: The specified key does not exist.
Key: get
RequestId: A3D2459C4D6ADDFC
HostId: az6HotmU3f1NaqQFEzyL+j7qseHDFIL4hwJrzCFJoPPY4gLFae5IoB2HHN5uoUe85ASO4EO1s38=
# I figure out that in Static website hosting s3 bucket is to fill index.html as an error HTML file in Error document.
