### ISSUE TITLE
Create wireframes

### ISSUE THREAD

**Issue by coultergeist** [ActoKids/AD440_W19_CloudPracticum#7]
Create wireframes: create events that communicate with API Team
- API call for Events List and Event description
- Used with API for data model
- Provide user access information

**Comment by coultergeist** [comment]
Estimated Time: 10 hours
Time to date: 6 hours

**Comment by coultergeist** [comment]
1/12 Link to [demo video](https://www.youtube.com/watch?v=ryG7mJzb414) on YouTube. Working with Yuan to get app access, a list of current screens, and those the client wants to create. 

1/16 Yuan shared this [prototype](https://projects.invisionapp.com/share/FPBK1Z9SM#/screens/231984513_2-_Map_View) of the app.

**Comment by coultergeist** [comment]
Wireframe
<img width="717" alt="actokids-wireframe" src="https://user-images.githubusercontent.com/16545169/51289505-45a92a00-19b5-11e9-96fb-7b4276afeb34.png">

Home Page
<img width="745" alt="actokids-home-wireframe" src="https://user-images.githubusercontent.com/16545169/51289168-06c6a480-19b4-11e9-8e89-ab6184616c41.png">
 
Activities Page
<img width="529" alt="actokids-activities-wireframe" src="https://user-images.githubusercontent.com/16545169/51289225-3675ac80-19b4-11e9-9e86-4e261223c53d.png">

Calendar Page
<img width="836" alt="actokids-calendar-wireframe" src="https://user-images.githubusercontent.com/16545169/51289229-3b3a6080-19b4-11e9-9ac5-09225eb9a31a.png">

About Page
<img width="849" alt="actokids-about-wireframe" src="https://user-images.githubusercontent.com/16545169/51289239-41c8d800-19b4-11e9-9f9a-2d429d73c121.png">

Account Page: Login or Create Account 
<img width="835" alt="actokids-account-home-wireframe" src="https://user-images.githubusercontent.com/16545169/51289280-66bd4b00-19b4-11e9-9d17-f87c9c317686.png">

Create Account 
<img width="834" alt="actokids-create-account-wireframe" src="https://user-images.githubusercontent.com/16545169/51289284-6c1a9580-19b4-11e9-9c15-44bf9a1234c1.png">

Create Event
<img width="423" alt="actokids-create-event-wireframe" src="https://user-images.githubusercontent.com/16545169/51289290-72107680-19b4-11e9-81b4-335f05dac864.png">

Contact Page
<img width="814" alt="actokids-contact-wireframe" src="https://user-images.githubusercontent.com/16545169/51289294-76d52a80-19b4-11e9-8052-5018161a4dcf.png">

**Comment by coultergeist** [comment]
I still need to:

1. Create wireframe of the SuperAdmin role to show approve/delete activity function
2. Add facebook/3rd auth to login screen (if needed)
3. Any other needs?

<img width="835" alt="actokids-account-home-wireframe" src="https://user-images.githubusercontent.com/16545169/51291432-fa464a00-19bb-11e9-8a8d-0710dcf17cf7.png">

**Comment by coultergeist** [comment]
Talked with the client (Yuan) today about the Admin roles/permissions. She is happy with "Organization" and "Admin" as the roles. Organizers can create events. Events need to be approved by an Admin. Once events are approved, organizers can update event without needing another approval. Events will have the following fields: organization and location (based upon text input like city or zip).

**Comment by erikNeville** [comment]
Created an authentication flow wireframe using permissions outlined by Danielle above
![image](https://user-images.githubusercontent.com/27576296/51507235-d6f91180-1da4-11e9-9068-0e0ece0ab861.png)

This task took me about 6 hours.

**Comment by coultergeist** [comment]
WikiLink: https://github.com/ActoKids/AD440_W19_CloudPracticum/wiki/Wireframes
