### ISSUE TITLE
Chromedriver error, OFA Lambda

### ISSUE THREAD

**Issue by mrvirus9898** [ActoKids/AD440_W19_CloudPracticum#75]
Currently, there is a bug on the AWS deployed version of the Outdoors For All (OFA) crawler. When the crawler executes, it returns status 200, but throws an error: 
START RequestId: b1221dd8-879f-46b7-be4b-c8ea410bec1d Version: $LATEST

Checking for linux64 chromedriver:2.46 in cache
There is no cached driver. Downloading new one...
Trying to download new driver from http://chromedriver.storage.googleapis.com/2.46/chromedriver_linux64.zip
Unpack archive /tmp/chromedriver.zip
Error gathering URL data, Message: 'chromedriver.exe' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

Closing OFA Crawler; 2019-02-23 04:47:51.310210
END RequestId: b1221dd8-879f-46b7-be4b-c8ea410bec1d
REPORT RequestId: b1221dd8-879f-46b7-be4b-c8ea410bec1d	Duration: 2684.79 ms	Billed Duration: 2700 ms 	Memory Size: 128 MB	Max Memory Used: 93 MB	

The EC2 instance running on AWS does not have chromdriver installed, and when it attempts to install, it throws an error.

**Comment by mrvirus9898** [comment]
Add the following Environmental Variables:
PATH = /var/task/bin
PYTHONPATH = /var/task/src:/var/task/lib

This has saved the step of downloading the .zip however, the bug remains the same.

The error is the following:
START RequestId: 71953a2c-6218-4bf8-b675-1044fafe47cd Version: $LATEST

Checking for linux64 chromedriver:2.46 in cache
Driver found in /tmp/chromedriver
Error gathering URL data, Message: 'chromedriver.exe' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home


Closing OFA Crawler; 2019-02-23 05:21:05.704851
END RequestId: 71953a2c-6218-4bf8-b675-1044fafe47cd
REPORT RequestId: 71953a2c-6218-4bf8-b675-1044fafe47cd	Duration: 48.22 ms	Billed Duration: 100 ms 	Memory Size: 128 MB	Max Memory Used: 68 MB

**Comment by mrvirus9898** [comment]
@mrvirus9898  time: 2 hours
@MikeJLeon time: 6 hours

I am not sure how much time Dao spent.

Fix: Abspath was used to have the system OS locate the chromedriver. pathtest was added to that we can see what the path is, and that is displayed in the absolutemadpath key.

    driver = webdriver.Chrome(executable_path=os.path.abspath("chromedriver"))
    pathtest = os.path.abspath("chromedriver")

However another error has occurred which will be written up.

**Comment by daonguyen81** [comment]
I spent the last 4 days and couldn't figure it out why it's not working the way we want it to work.
I found some source that we might want to implement witht Lambda:
[https://medium.com/the-apps-team/running-selenium-and-headless-chrome-on-aws-lambda-layers-python-3-6-bd810503c6c3](url)

**Comment by MikeJLeon** [comment]
This issue is no longer relevant
