### ISSUE TITLE
Chromedriver permission error, OFA Lambda

### ISSUE THREAD

**Issue by mrvirus9898** [ActoKids/AD440_W19_CloudPracticum#76]
Related to #75 

Time Spent so far
@mrvirus9898 : 3
@MikeJLeon : 3
@T-travis : 2

Chromedriver's path has been resolved, but now we are getting a different error, where the driver does not seem to have execution permissions to accomplish what it needs to do. When a user uploads the .zip file, and executes a test, the following error will be thrown.

Error gathering URL data, Message: 'chromedriver.exe' executable may have wrong permissions. Please see https://sites.google.com/a/chromium.org/chromedriver/home

Steps to reproduce this bug:
1. Download this zip -> https://drive.google.com/open?id=1eqPXHXrxFkR4kSV0v7KbOnsONzV0x_Tf
2. Go to AWS Lambda
3. Upload this zip file to a function
4. Add Environmental Variables to PATH:/var/task/bin, and PYTHONPATH:/var/task/lib 
5. Set time out timer to 10 seconds
6. Save
7. Select a test, or create a test; the basic test maybe used
8. Run this test
9. Lambda will indicate a success, but expand the logs and you will find the permission error.

What we know so far:
*This bug does not seem related to DevOps permissions, as we have tested this on private accounts and the bug still exists
*This bug exists if we use either chromedriver or chromedriver.exe, and this if we use abspath, or "/var/task/chromedriver"
*Travis downloaded a copy of the zip file, changed the execution permission in linux, and tried the lambda, but got the same error.
*os.system() commands did not seem to change the permissions of the AWS container (which makes some sense) however, not all os.system() commands are locked out. 
*This bug is triggered the function ofa_crawl(), and it is not a fatal error.

References used: https://medium.com/@manivannan_data/python-selenium-on-aws-lambda-b4b9de44b8e1

**Comment by MikeJLeon** [comment]
Very mean bug, it is making the whole code totally useless without Selenium. I've tried all these steps youve mentioned as well and there is no luck at all, may need a team effort to solve this.

**Comment by daonguyen81** [comment]
I spent 5 hours today and couldn't figure it out what is wrong with the permissions. I will resume my research again the next morning.

**Comment by MikeJLeon** [comment]
I've came up with a solution to move this script to EC2, I've asked Anar to set me up with a instance. It has proven to be working on the instance now. Just need to talk about if we need to go with this path.

**Comment by MikeJLeon** [comment]
Upon toddy's recommendation I have tried using a layer. Unfortunately still getting a permission error despite using it. 
![permission error](https://user-images.githubusercontent.com/6200669/53547485-060d4c00-3ae4-11e9-9324-2597efbfd294.PNG)

**Comment by MikeJLeon** [comment]
I have decided to use EC2 over Lambda. It seems to be working,  I am closing this issue for now.
