### ISSUE TITLE
UITeam Permissions

### ISSUE THREAD

**Issue by coultergeist** [ActoKids/AD440_W19_CloudPracticum#77]
Lyndon/DevOps,

I'm having some issues with my permissions. I thought it would be helpful to DevOps to try and define exactly what perms I think I'll need moving forward. I hope this list helps, and that's it's exhaustive. 

- API Gateway - FULL ACCESS
- PINPOINT - FULL ACCESS to create analytics dashboard
- Cognito - Enough access to read user pools, to read CloudWatch logs
- Lambda - Either access to lambda to create a test function to be able to test the complete API, or I need the actual endpoint we will be using
- CloudWatch

**Comment by LyndonP** [comment]
Danielle, I've made a couple changes, can you try again?

**Comment by coultergeist** [comment]
Hi @LyndonP. Sorry, just now getting to try them. Looks like I don't have Cognito, unless I'm doing it wrong: 

AWS>Cognito>Create User Pool>_name pool_>Review defaults....>Create then I see this error

<img width="953" alt="cognito-error" src="https://user-images.githubusercontent.com/16545169/53687862-fa41a580-3cee-11e9-94dd-f37e78d6ab25.png">

**Comment by LyndonP** [comment]
Hi @coultergeist can your try once more when you have a chance and let me know?

**Comment by coultergeist** [comment]
Perms update still preventing the creation of a user pool. See error message below.
<img width="1212" alt="screen shot 2019-03-05 at 2 13 40 pm" src="https://user-images.githubusercontent.com/16545169/53841428-9834aa80-3f51-11e9-8bd8-0f6c0c4b9b1f.png">

**Comment by zach-daniels** [comment]
For DevOps:

Error messaging when attempting to create _user pool_: 

"**There was a problem creating your user pool. Please try again.**"

Possible solutions:

https://forums.aws.amazon.com/thread.jspa?messageID=865288
https://forums.aws.amazon.com/thread.jspa?messageID=781912

Both of those links refer to the "AmazonCognitoPowerUser" permission. 

Error messaging when attempting to access _Identity Pools_: 

"**You do not have permissions to access the Amazon Cognito console. Please contact your system administrator for access."**

**Comment by LyndonP** [comment]
@coultergeist I've made some additional changes, can you try once more? Thanks for your patience while we get to the bottom of this.

**Comment by coultergeist** [comment]
@LyndonP There are two Cognito functions:
1) "Manage User Pools" - I am able to fully create a user pool.
2) "Manage Identity Pools" - Not authorized 
`User: arn:aws:iam::061431082068:user/danielle.coulter@seattlecolleges.edu is not authorized to perform: iam:CreateRole on resource: arn:aws:iam::061431082068:role/Cognito_ActoKidsAuth_Role`

Note: I (believe) I need DevOps to create a policy and a role that allows the people logging in to actually invoke the API.

**Comment by LyndonP** [comment]
Received confirmation that this is no longer an issue. To resolve this, I added IAM:CreateRole to Danielle's individual account.
