### ISSUE TITLE
I am getting invalid security token when testing Role-Based-Access-Control with Cognito

### ISSUE THREAD

**Issue by toddysm** [ActoKids/AD440_W19_CloudPracticum#78]
I was going through the steps of testing #29 as described in https://github.com/ActoKids/api/wiki/Role-Based-Access-Control and I am getting the following response:
```{
    "message": "The security token included in the request is invalid."
}
```
Here is a screenshot from the Postman request: 
![image](https://user-images.githubusercontent.com/1007103/53450841-2a790380-39d2-11e9-9b3e-bbd29385bb46.png)

**Comment by zach-daniels** [comment]
The tokens assigned by Cognito's identity pool are temporary, so they only last for 1-12 hours. For what it's worth, I stated the token's expiration date and time on the Wiki when the credentials were made last week. Unfortunately, this means the tokens most likely need to be refreshed on-demand for testing purposes.

**Comment by ZakBrinlee** [comment]
Closing this issue as it was not a bug issue. We have addressed some of the Cognito issues with the front end for a deliverable of Cognito access.
