### ISSUE TITLE
Grant full access to Lambda Layers

### ISSUE THREAD

**Issue by MikeJLeon** [ActoKids/AD440_W19_CloudPracticum#79]
Crawler team requires full access rights to utilize Lambda Layers, I am unable to test currently due to this restriction.

**Comment by jams2018** [comment]
The policy is changed and it has included the full access to lambda layers as requested. Can you test it and let us know?

**Comment by MikeJLeon** [comment]
@jams2018 it is currently still not working

User: arn:aws:iam::061431082068:user/michaeljleon@live.com is not authorized to perform: kms:ListAliases on resource: *

You are not authorized to perform: iam:PassRole.

these are the errors currently when applying a new layer to a function.

**Comment by jams2018** [comment]
ok. I am looking into it now again.

**Comment by MikeJLeon** [comment]
@jams2018 still no permissions
ad440-w19-lambda-crawler-ofascraper
You are not authorized to perform: lambda:UpdateFunctionConfiguration. is the new error.

**Comment by daonguyen81** [comment]
I still don't have permissions to access the Lambda Layers. 
ad440-w19-lambda-crawler-ofascraper

You are not authorized to perform: cloudformation:DescribeStackResources.


User: arn:aws:iam::061431082068:user/dao.nguyen425@yahoo.com is not authorized to perform: kms:ListAliases on resource: *


Configuration
Monitoring

**Comment by LyndonP** [comment]
> I still don't have permissions to access the Lambda Layers.
> ad440-w19-lambda-crawler-ofascraper
> 
> You are not authorized to perform: cloudformation:DescribeStackResources.
> 
> User: arn:aws:iam::061431082068:user/dao.nguyen425@yahoo.com is not authorized to perform: kms:ListAliases on resource: *
> 
> Configuration
> Monitoring

@daonguyen81 can you try again and let me know how it goes?

**Comment by MikeJLeon** [comment]
@LyndonP I am getting this error for layers "You are not authorized to perform: lambda:UpdateFunctionConfiguration."

**Comment by MikeJLeon** [comment]
Lets go ahead and close this for now, we may not need to bother with this.
