### ISSUE TITLE
Ec2 instance 

### ISSUE THREAD

**Issue by MikeJLeon** [ActoKids/AD440_W19_CloudPracticum#81]
I've asked @jams2018  (Anar) to create a ec2 instance for me. OfaScraper is failing to work with lambda due to the environment. Bottom line the lambda environment does not grant permission for chromedriver to run. Creating our own ec2 bypasses this issue.

**Comment by MikeJLeon** [comment]
I also require an access key.

**Comment by jams2018** [comment]
The access key is provided.
