### ISSUE TITLE
Production Environment Lambdas

### ISSUE THREAD

**Issue by mrvirus9898** [ActoKids/AD440_W19_CloudPracticum#83]
Related to #70, three lambdas will be needed, with production roles, for out production lambdas. This can be accomplished in two ways.

Create three more Lambdas with Production roles, and Production in their names. 
Or 
Rename three lambdas, and assign those lambdas with production rolls. 

Either way works.

**Comment by jams2018** [comment]
Three Lambda functions have been created as requested.

ad440-w19-lambda-crawler-prod1
ad440-w19-lambda-crawler-prod2
ad440-w19-lambda-crawler-prod3

**Comment by jams2018** [comment]
Please let me know if you have any issues this.

**Comment by mrvirus9898** [comment]
Thank you @jams2018 Closing issue now.

**Comment by jams2018** [comment]
![83](https://user-images.githubusercontent.com/38123178/53783500-a4275a80-3ec6-11e9-9f2d-7c42e18a7060.PNG)

**Comment by jams2018** [comment]
@mrvirus9898 I've created 3 lambda functions with 3 different roles. Dev, Prod, and Full and deleted the functions created previously.

ad440-w19-lambda-crawler-dev
ad440-w19-lambda-crawler-prod
ad440-w19-lambda-crawler-full
