### ISSUE TITLE
Lambda to Ec2 policy access 

### ISSUE THREAD

**Issue by MikeJLeon** [ActoKids/AD440_W19_CloudPracticum#84]
I am currently trying to have lambda trigger the EC2 instance. It is not currently authorized to perform such an action. Could someone from the devop's team provide access for the lambda to trigger ec2? While youre at it can you also allow ec2 to write to cloudwatch?

https://aws.amazon.com/premiumsupport/knowledge-center/start-stop-lambda-cloudwatch/

**Comment by Stakada** [comment]
Edited Crawler lambda policy.

**Comment by MikeJLeon** [comment]
Lambda still has no permission for the instance.

**Comment by MikeJLeon** [comment]
Encoded error message, if this is useful to figure out whats going on you will need to decode this as an admin -
Lw3R0-GDl2DrgiA8EvbVGXUCTbSAo-EyE5VMGI4YR8r_fLPm4AbI-KBwr-COEugonSvp-OyWDVRyqPiktYOA5hT3mwmYZ1TBkF-m6Zei6SM1WqVPodOokvkqhPkM_zD117ZiffzuacFry7YweNGhpJPnsYc0k6zqi1UVI2U9H3GAN8I9TYFIqIFHAbU15iE9t12msyLnIQMMOGWM6B4GPt2hCC8j8EtsK4_ox4drlpGx6emXn5R0udrbQyMVMjxsA4hjzjD0eXjuqi7z8cIIVKo9hSC10kpDnQ9lV9EfoGcmFq-ABgZ8GWUCPcBAaRwirARcSiY2Q41mt27s7ErMRwVkEJYHK1veoXO6dbLuCJbRQEQVtADtbQBXIMjMNHESEC6pQMqYlWE4xy7KFs3cLwgp2wNFJyREOOcT5UFZpnFvAaGIkpA1qkjj06wOqnewvdDeG9oj_F5joXhqXnF-CwUGDJI7eek0mjDxYtFsCJPXGnaYlqDiUjska-S8-b3JMTj3W3x_fNUFk9S7YNsokl8MpeZzVieVoF90mXsqianbn8WPAW8mS-CIzgVKliGNByiLg3LHeZ59zpAmeJfIVAfKmVyEgjdBLctPt6HIcbenOtuE9U3MThlt-me9LuPW25qLpX6hbUxBWD1W2ohbcRvQc5LjCB2uJWRClIHMfqaK8jufeVwuuxmEpIOKUkO5GdVNmFbxPYXnvIbOYFZwEEe_HLvJQGO7MVLGXZEJUR5z9w

**Comment by Stakada** [comment]
Edited EC2 policy attached to Lambda-S2-and-Dynamo-Full role.

**Comment by MikeJLeon** [comment]
Thanks shota, Code works now!

**Comment by Stakada** [comment]
<img width="388" alt="screen shot 2019-03-03 at 3 44 29 pm" src="https://user-images.githubusercontent.com/34498187/53703866-642f7d00-3dcb-11e9-884d-cadd6093d574.png">

Added start and end action to ad440-w19-lambda-ec2-crawler policy attached to this role ( https://console.aws.amazon.com/iam/home?region=us-east-2#/roles/NSC2019_Lambda-S2-and-Dynamo-Full )
<img width="402" alt="screen shot 2019-03-03 at 3 44 23 pm" src="https://user-images.githubusercontent.com/34498187/53703871-6f82a880-3dcb-11e9-8780-9fb20f412840.png">
