### ISSUE TITLE
Need longer execution time for Lambda

### ISSUE THREAD

**Issue by rberry206** [ActoKids/AD440_W19_CloudPracticum#85]
Error:   "errorMessage": "2019-03-03T21:06:51.860Z 3e446190-937d-42db-bc6a-c1ba68de68cb Task timed out after 3.00 seconds"

Task time should take no longer than 6 seconds.

**Comment by LyndonP** [comment]
@rberry206  I've made some changes. Can you verify if has updated on your end?

**Comment by rberry206** [comment]
Original Error:
![lambdaerror](https://user-images.githubusercontent.com/34557901/53702797-bbc7eb80-3dbf-11e9-961e-3b1400dd2768.PNG)

FIXED:
![fixedlambda](https://user-images.githubusercontent.com/34557901/53702809-e0bc5e80-3dbf-11e9-98b4-bbdf5e755a7c.PNG)

I can confirm that Lyndon gave me access to a longer runtime.

**Comment by LyndonP** [comment]
![image](https://user-images.githubusercontent.com/34604046/53702951-2b8aa600-3dc1-11e9-9484-e8ea7dfd0082.png)

Changed up the setting for the Lambda Function (ad440-w19-lambda-crawler-googlecrawler) to a 1 Minute run time. 

Estimated Time:
5 Minutes
Actual Time:
5 Minutes
