### ISSUE TITLE
New Lambda or Rename

### ISSUE THREAD

**Issue by MikeJLeon** [ActoKids/AD440_W19_CloudPracticum#86]
Hey @ActoKids/devops , I've been holding back from asking for this since I wanted to make sure I could make it work first. I have been using ad440-w19-lambda-crawler-sscrawler for my ec2 testing but now it is ready to have a proper name, could we rename this function or create a duplicate with a name thats like **ad440-w19-lambda-crawler-LaunchEc2**

Thank you!

**Comment by MikeJLeon** [comment]
Also make sure this lambda has the same exact policies / roles as the sscrawler

Thanks.

**Comment by jams2018** [comment]
@MikeJLeon 

A new lambda function is created and it should have the same features that the current function contains.

"arn:aws:lambda:us-east-1:061431082068:function:ad440-w19-lambda-crawler-launchec2"

**Comment by jams2018** [comment]
![86](https://user-images.githubusercontent.com/38123178/53784756-287bdc80-3ecb-11e9-8339-46d6dedd6585.PNG)

**Comment by jams2018** [comment]
The issue is closed due to a successful launch of the function.
