### ISSUE TITLE
Permissions Request, Lambdas and Cloudwatch Triggers

### ISSUE THREAD

**Issue by mrvirus9898** [ActoKids/AD440_W19_CloudPracticum#88]
AddPermission on resources and UpdateFunctionConfiguration errors are being thrown when common task are needed to be done.

AddPermission is thrown when a Crawler team member tries to set up a trigger for a Lambda. The team member can create the trigger, but can not add the permission to the Lambda that enables the two to work together. @kyrrahnork and @mrvirus9898 will both need to be able to addpermissions

Steps to reproduce
1) Go to cloudwatch
2) Click on rules
3) Select SSSCrawler
4) No rules are written there because of error
5) Edit these rules
6) Add Target ssscrawler
7) Click configuration details and update rule
8) AddPermission Error will be thrown

Secondly 

1) Go to Lambdas
2) Scroll to the Prod lambda and click on it
3) Scroll down to the timer
4) Change timer from 3 to 10 seconds
5) Click save, and test the lambda
6) Lambda will throw an error, UpdateFunctionConfiguration

**Comment by jams2018** [comment]
@mrvirus9898 

The timeout limit has been increased. It should solve the 2nd issue.

**Comment by mrvirus9898** [comment]
Thanks Anar, we will talk about this more in class

**Comment by MikeJLeon** [comment]
@bmenaz gave me permissions to production lambda and @Stakada gave me permission to Dynamo. Thanks guys, issue closed.
