### ISSUE TITLE
Error with OFA scraper.

### ISSUE THREAD

**Issue by daonguyen81** [ActoKids/AD440_W19_CloudPracticum#89]
I ran the test on OFA scraper several times this morning and I found out that there is an error occurred with this file after the script finishing scrapping the first month of data. 

Error gathering URL data, An error occurred (ValidationException) when calling the PutItem operation: One or more parameter values were invalid: An AttributeValue may not contain an empty . 

I run the script locally on my machine 10 times and passed 10 times. We might want to double check the execution time on EC2 where the script is deployed.

**Comment by daonguyen81** [comment]
The OFA scraper didn't run into error last night and this morning when I tested it. The admin of the [https://outdoorsforall.org/events-news/calendar/](https://outdoorsforall.org/events-news/calendar/) just added in a lot of new events to this calendar, then the error is found. I believe the execution time might be off.

**Comment by MikeJLeon** [comment]
I am working on a fix now, thanks for mentioning this Dao!

**Comment by MikeJLeon** [comment]
Error is fixed, let me know if anything else pops up. Thank you Dao.
