### ISSUE TITLE
UI Fixes

### ISSUE THREAD

**Issue by coultergeist** [ActoKids/AD440_W19_CloudPracticum#92]
For this final sprint: Perform UI fixes based on client feedback. _See Danielle and the [Demo Issue](https://github.com/ActoKids/AD440_W19_CloudPracticum/issues/91) for for more info_:

### Nav bar
1) Ensure the nav bar has proper elements showing/hiding when necessary. Refer to [issue # 93](https://github.com/ActoKids/AD440_W19_CloudPracticum/issues/93)
User Logged in Logic
### Create Event Page
1) Handle radio buttons. Either make them vertical or change them into radio buttons.

### Disability Types 
(working with Alex from API team):
1) Add "inclusive" 
2) Add "Other" with a text box 

### Event Dashboard CRUD features
Need to address the Delete, Edit, Done buttons. For example, is the API team even set up for Delete multiple? Can you edit more than one event at a time? (Probably not. I recommend removing the edit button all together as an Admin can click on each event and edit it there.) Recommendation from Toddy: Make those 3 options available on each event in the list instead of options for all in the list.

Once assigned, annotate your estimated time. Then, keep regular updates on your issue. Comment your approach, tutorials, articles, updates, links, photos, etc. Comment often. When closing your issue include the following in your final comment.

Time estimated:
Time spent:
Pull Request link:
Wiki link:
Deployed Code link:
Testers:
What I tested:

**Comment by bradleyshao** [comment]
Estimate: 10 hrs
Current: 5 hrs
I separate the form to three parts: event information, Organization information and AddressTime.
trying to add "Selectrix" to the project, for the disability_type multi select, because the materialize multi-select is not working.

**Comment by bradleyshao** [comment]
<img width="1276" alt="屏幕快照 2019-03-20 12 42 11" src="https://user-images.githubusercontent.com/34496812/54714277-ca2b3c80-4b0d-11e9-94c2-af50b8405021.png">
<img width="1278" alt="屏幕快照 2019-03-20 12 42 25" src="https://user-images.githubusercontent.com/34496812/54714280-cb5c6980-4b0d-11e9-9324-aa7e394f2d1c.png">
<img width="1280" alt="屏幕快照 2019-03-20 12 42 38" src="https://user-images.githubusercontent.com/34496812/54714283-cc8d9680-4b0d-11e9-8acb-4e67d6ef20ba.png">
<img width="1278" alt="屏幕快照 2019-03-20 12 42 48" src="https://user-images.githubusercontent.com/34496812/54714290-cdbec380-4b0d-11e9-9ff4-9d4dc9e246a5.png">
<img width="745" alt="屏幕快照 2019-03-20 17 47 38" src="https://user-images.githubusercontent.com/34496812/54728027-771aaf00-4b38-11e9-8db2-a584e74db1a1.png">

**Comment by bradleyshao** [comment]
Estimate: 10 hrs
Actual :12 hrs
In this sprint, I separate the form into three sections: Event Information, Organization Information and Address&Time information, in order to make it more clear to users. In the CreateForm.js (event information), I made all the radio buttons vertical. Added two more options to the disability type. Add a function to the code that fixed the problem that allowed user to remove the type from array when they unselect it, the pervious code will keep adding types to array only.

**Comment by bradleyshao** [comment]
Pull request reviewed --https://github.com/ActoKids/web-ui/pull/45#pullrequestreview-215883320
https://github.com/ActoKids/web-ui/pull/46#pullrequestreview-215892132
Wiki page --https://github.com/ActoKids/web-ui/wiki/Form-Fix
Pull request -- https://github.com/ActoKids/web-ui/pull/48
https://github.com/ActoKids/web-ui/pull/55
Deployed Code link-- www-dev.2edusite.com
