### ISSUE TITLE
Connect to the APIs

### ISSUE THREAD

**Issue by coultergeist** [ActoKids/AD440_W19_CloudPracticum#94]
For this final sprint, ensure that all connections and data presented are pulling from the official APIs. See also the [Demo Issue](/events) for more info. 

- GET /events
- POST /events
- PUT /events
- DELETE /events

Once assigned, annotate your estimated time. Then, keep regular updates on your issue. Comment your approach, tutorials, articles, updates, links, photos, etc. Comment often. When closing your issue include the following in your final comment.

Time estimated:
Time spent:
Pull Request link:
Wiki link:
Deployed Code link:
Testers:
What I tested:

**Comment by erikNeville** [comment]
So far I can confirm that we are successfully connected to the GET and POST methods of the API.

Estimated Time: 15 hours

**Comment by erikNeville** [comment]
I've done a number of things to ensure that we are connected to API endpoints and that the app is functioning as a whole. 

See https://github.com/ActoKids/web-ui/commit/ca80a2e3c8101805f2a1cfc28125f304f6b29384 to see how I've ensured that props are passed to the UpdateEvent component properly.

See https://github.com/ActoKids/web-ui/commit/6e95f9d3fc932875553f577a526957b957ce8057 to see how I've passed props from EventList to EventDetails.

These changes were to ensure that we actually have the ability to test API functionality. 

Bugs that I've worked on so far:
https://github.com/ActoKids/AD440_W19_CloudPracticum/issues/113 with @dashinay 
https://github.com/ActoKids/AD440_W19_CloudPracticum/issues/107 with @Enshaedn 
https://github.com/ActoKids/AD440_W19_CloudPracticum/issues/106 with @hkhual  and @ZakBrinlee
https://github.com/ActoKids/AD440_W19_CloudPracticum/issues/114 with @hkhual  
and https://github.com/ActoKids/AD440_W19_CloudPracticum/issues/112 which is currently open

I've also been assisting the rest of the team members with the functionality of their tasks and react development. Here are the tasks I've been assisting in:
https://github.com/ActoKids/AD440_W19_CloudPracticum/issues/118
https://github.com/ActoKids/AD440_W19_CloudPracticum/issues/91

Code review of @zphupro : https://github.com/ActoKids/web-ui/pull/43

Link to my most recent pull request:
https://github.com/ActoKids/web-ui/pull/37

Time so far on this task is 18 hours

All connections to the API are possible, but previous tasks involving those calls (DELETE, and PUT) were not completed on the UI side. Displayed on www-dev.2edusite.com are methods for GET and POST.

Link to all of my PRs: https://github.com/ActoKids/web-ui/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3AerikNeville+
